#!/bin/bash

case $1 in
"--name")
  fullname=$(getent passwd "$(whoami)" | cut -d ':' -f 5 | cut -d ',' -f 1 | tr -d "\n")
  if [ -z "$fullname" ]; then
    echo "$(whoami)@$(hostnamectl | awk 'FNR==1 {print $3}')"
  else
    echo "$fullname"
  fi
  ;;
"--kernel")
  echo "$(uname -r)"
  ;;
"--os")
  echo "$(cat /etc/os-release | awk 'NR==1' | awk -F '"' '{print $2}')"
  ;;
"--pkgs")
  echo "$(yay -Q | wc -l)"
  ;;
"--wm")
  echo "$(xprop -id $(xprop -root -notype | awk '$1=="_NET_SUPPORTING_WM_CHECK:"{print $5}') -notype -f _NET_WM_NAME 8t | grep "WM_NAME" | cut -f2 -d \")"
  ;;
esac
